language: java
notifications:
  email:
  - nonni95@gmail.com
  - maggisig92@gmail.com
  - hilmarragnars@gmail.com
jdk:
- openjdk7
- oraclejdk7
before_script:
- ./gradlew check
- eval $(ssh-agent)
- chmod 600 .travis/staging_deploy_key.pem
- ssh-add .travis/staging_deploy_key.pem
- git remote add deploy git@heroku.com:erkimoddarar-staging.git
- git push deploy
script:
- ./gradlew seleniumXvfb