language: java
notifications:
  email:
  - nonni95@gmail.com
  - maggisig92@gmail.com
  - hilmarragnars@gmail.com
jdk:
- openjdk7
install:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku plugins:install https://github.com/ddollar/heroku-push
script:
- ./gradlew check
- heroku push --app erkimoddarar-staging
- ./gradlew seleniumXvfb
after_success:
- chmod +x bin/update-gh-pages.sh
- ./bin/update-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: T1A92Eo2CQtMXOE8XQGlrl6h4W3tDcyOxSiAF4HKd7w+OlvCFSgWtwNHpP4aaudaJ3GOqjP3iNT+UyP/6pZPzsffr0W8/z/wcQGDZ6rThBfCYPPFlm/qrhSr4dUBzXyhJEmuuc8xc0jw+9MjKLyCaH4PzbuFYmyJtkmKvshPah0=
  app: erkimoddarar
  on: master
env:
  matrix: 
  global:
  - secure: hkXT/VBCBm5dagOucVNFWDUqC9dGb8f7IOIc5gqO/8YuJ2a4xJWPMHNvYk72CAKyrS+1ClZ+PBAOCvob4NBNH+02olJldm5H7UYDm+bJDcOnYddSezIM6QPL5Zl8PJ7f9XtgC/uvrxAmOlatNUHx4iqzLyhoRXc6+wNhlMiQxg0=
  - secure: YvQwNrrHEntk6hOZd4UVZJuC/pPfaAziCcNToEkHPzk7dAlltt5T+MprEWk05VVBvs9ORsYHd+XFIkMhnD4ZS3zhqlZUE1rRWg/EzHV4W68GjcqqIz6eq9+J+RDFAzucN9vbZKgbYTPhtCMvgez7HBXqpU5dr7xcZ80pJBa/Dps=
