language: java
notifications:
  email:
  - nonni95@gmail.com
  - maggisig92@gmail.com
  - hilmarragnars@gmail.com
jdk:
- openjdk7
- oraclejdk7
before_script:
- ./gradlew check
#- eval $(ssh-agent)
#- chmod 600 .travis/staging_deploy_key.pem
#- ssh-add gudCFkB1lDkAnRYB9HqWYv2wfaOJnOfDHY+PhRfQMlahx0dgyacek00OlQsfbyb/O0T437i4pXCjZy1UXl/1TzX2hpgoA9prlSHPgDUlhEEAXsNcxnFaas33fYVUDWU01OWB44TV6mQbZlsjMOPw3mfCmTKTQ6yJ160um+VJr9s=
- git remote add deploy git@heroku.com:erkimoddarar-staging.git
- git push deploy
script:
- ./gradlew seleniumXvfb
deploy:
  api_key:
    secure: gudCFkB1lDkAnRYB9HqWYv2wfaOJnOfDHY+PhRfQMlahx0dgyacek00OlQsfbyb/O0T437i4pXCjZy1UXl/1TzX2hpgoA9prlSHPgDUlhEEAXsNcxnFaas33fYVUDWU01OWB44TV6mQbZlsjMOPw3mfCmTKTQ6yJ160um+VJr9s=
