language: java
notifications:
  email:
    - nonni95@gmail.com
    - maggisig92@gmail.com
    - hilmarragnars@gmail.com
jdk:
    - openjdk7
    - oraclejdk7
script:
    - ./gradlew check
    - ./gradlew seleniumXvfb