language: java
notifications:
  email:
  - nonni95@gmail.com
  - maggisig92@gmail.com
  - hilmarragnars@gmail.com
jdk:
- openjdk7
- oraclejdk7
before_script:
- ./gradlew check
- cat $STAGING_KEY > .travis/staging_deploy_key.pem
- chmod 600 .travis/staging_deploy_key.pem
- ssh-add .travis/staging_deploy_key.pem
- git remote add deploy git@heroku.com:erkimoddarar-staging.git
- git push deploy
script:
- ./gradlew seleniumXvfb
env:
  matrix:
    secure: LfJgZmBOZjt52Ih6o14XShFisij1SLrStv/+ZnitJ6/J3rSKtryFIBMtfaEU/+pV9r4K6Kck50d9CytR5nBhR+byXl8wckl+Gs1VlcrRXzlpNyQtLYIGxTJ8RBFXzjrtD8xsp49mkL8uunDDbjT1A1XDaBQx0O17LL0v//TfAeU=
